version: "2"
services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - "elasticsearch:elasticsearch"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
  fluentd:
    build: ./fluentd
    ports:
      - "24224:24224"
    depends_on:
      - elasticsearch
    links:
      - "elasticsearch:elasticsearch"
    volumes:
      - "$HOME/tmp:/home/fluent/logs"
